# Copyright (c) 2020, NVIDIA CORPORATION. All rights reserved.

obj-$(CONFIG_TEGRA_5G_LDPC) += ldpc/

obj-$(CONFIG_TEGRA_DCE) += dce/
obj-$(CONFIG_TEGRA_SPE) += aon/

obj-$(CONFIG_TEGRA_MCE) += mce/
obj-$(CONFIG_TEGRA_PSC) += psc/

obj-$(CONFIG_TEGRA_CACHE) += cache/

