ccflags-y += -I$(srctree.nvidia)/drivers/video/tegra/host
ccflags-y += -I$(srctree.nvidia-t23x)/drivers/video/tegra/host
obj-$(CONFIG_TEGRA_T23X_GRHOST) += t23x/
obj-$(CONFIG_TEGRA_T23X_GRHOST) += pva/
