/*
 * Copyright (c) 2020, NVIDIA CORPORATION.  All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms and conditions of the GNU General Public License,
 * version 2, as published by the Free Software Foundation.
 *
 * This program is distributed in the hope it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#ifndef _DT_BINDINGS_TEGRA_ICC_ID_H
#define _DT_BINDINGS_TEGRA_ICC_ID_H

#define NV_PTCR2MC_SR_ID                      0
#define NV_MIU7R2MC_SR_ID                     1
#define NV_MIU7W2MC_SW_ID                     2
#define NV_MIU8R2MC_SR_ID                     3
#define NV_MIU8W2MC_SW_ID                     4
#define NV_MIU9R2MC_SR_ID                     5
#define NV_MIU9W2MC_SW_ID                     6
#define NV_MIU10R2MC_SR_ID                    7
#define NV_MIU10W2MC_SW_ID                    8
#define NV_MIU11R2MC_SR_ID                    9
#define NV_MIU11W2MC_SW_ID                   10
#define NV_MIU12R2MC_SR_ID                   11
#define NV_MIU12W2MC_SW_ID                   12
#define NV_MIU13R2MC_SR_ID                   13
#define NV_MIU13W2MC_SW_ID                   14
#define NV_HDAR2MC_SR_ID                     21
#define NV_HOST1XDMAR2MC_SR_ID               22
#define NV_NVENCSRD2MC_SR_ID                 28
#define NV_MPCORER2MC_SR_ID                  39
#define NV_PCIE6AR2MC_SR_ID                  40
#define NV_PCIE6AW2MC_SW_ID                  41
#define NV_PCIE7AR2MC_SR_ID                  42
#define NV_NVENCSWR2MC_SW_ID                 43
#define NV_DLA0RDB2MC_SR_ID                  44
#define NV_DLA0RDB12MC_SR_ID                 45
#define NV_DLA0WRB2MC_SW_ID                  46
#define NV_DLA1RDB2MC_SR_ID                  47
#define NV_PCIE7AW2MC_SW_ID                  48
#define NV_PCIE8AR2MC_SR_ID                  50
#define NV_PSCR2MC_SR_ID                     51
#define NV_PSCW2MC_SW_ID                     52
#define NV_HDAW2MC_SW_ID                     53
#define NV_MPCOREW2MC_SW_ID                  57
#define NV_OFAR12MC_SR_ID                    58
#define NV_PCIE8AW2MC_SW_ID                  59
#define NV_PCIE9AR2MC_SR_ID                  60
#define NV_PCIE6AR12MC_SR_ID                 61
#define NV_PCIE9AW2MC_SW_ID                  62
#define NV_PCIE10AR2MC_SR_ID                 63
#define NV_PCIE10AW2MC_SW_ID                 64
#define NV_ISPRA2MC_SR_ID                    68
#define NV_ISPFALR2MC_SR_ID                  69
#define NV_ISPWA2MC_SW_ID                    70
#define NV_ISPWB2MC_SW_ID                    71
#define NV_PCIE10AR12MC_SR_ID                72
#define NV_PCIE7AR12MC_SR_ID                 73
#define NV_XUSB_HOSTR2MC_SR_ID               74
#define NV_XUSB_HOSTW2MC_SW_ID               75
#define NV_XUSB_DEVR2MC_SR_ID                76
#define NV_XUSB_DEVW2MC_SW_ID                77
#define NV_TSECSRD2MC_SR_ID                  84
#define NV_TSECSWR2MC_SW_ID                  85
#define NV_XSPI1W2MC_SW_ID                   86
#define NV_MGBEARD2MC_SR_ID                  88
#define NV_MGBEBRD2MC_SR_ID                  89
#define NV_MGBECRD2MC_SR_ID                  90
#define NV_MGBEDRD2MC_SR_ID                  91
#define NV_MGBEAWR2MC_SW_ID                  92
#define NV_OFAR2MC_SR_ID                     93
#define NV_OFAW2MC_SW_ID                     94
#define NV_MGBEBWR2MC_SW_ID                  95
#define NV_SDMMCRA2MC_SR_ID                  96
#define NV_MGBECWR2MC_SW_ID                  97
#define NV_SDMMCRAB2MC_SR_ID                 99
#define NV_SDMMCWA2MC_SW_ID                 100
#define NV_MGBEDWR2MC_SW_ID                 101
#define NV_SDMMCWAB2MC_SW_ID                103
#define NV_SEU1RD2MC_SR_ID                  104
#define NV_SEU1WR2MC_SW_ID                  105
#define NV_DCER2MC_SR_ID                    106
#define NV_DCEW2MC_SW_ID                    107
#define NV_VICSRD2MC_SR_ID                  108
#define NV_VICSWR2MC_SW_ID                  109
#define NV_DLA1RDB12MC_SR_ID                110
#define NV_DLA1WRB2MC_SW_ID                 111
#define NV_VI2W2MC_SW_ID                    112
#define NV_VI2FALR2MC_SR_ID                 113
#define NV_VIW2MC_SW_ID                     114
#define NV_NVDISPNISOR2MC_SR_ID             115
#define NV_NVDISPNISOW2MC_SW_ID             116
#define NV_XSPI0R2MC_SR_ID                  117
#define NV_XSPI0W2MC_SW_ID                  118
#define NV_XSPI1R2MC_SR_ID                  119
#define NV_NVDECSRD2MC_SR_ID                120
#define NV_NVDECSWR2MC_SW_ID                121
#define NV_APER2MC_SR_ID                    122
#define NV_APEW2MC_SW_ID                    123
#define NV_VI2FALW2MC_SW_ID                 124
#define NV_NVJPGSRD2MC_SR_ID                126
#define NV_NVJPGSWR2MC_SW_ID                127
#define NV_SESRD2MC_SR_ID                   128
#define NV_SESWR2MC_SW_ID                   129
#define NV_AXIAPR2MC_SR_ID                  130
#define NV_AXIAPW2MC_SW_ID                  131
#define NV_ETRR2MC_SR_ID                    132
#define NV_ETRW2MC_SW_ID                    133
#define NV_DCEDMAR2MC_SR_ID                 136
#define NV_DCEDMAW2MC_SW_ID                 137
#define NV_AXISR2MC_SR_ID                   140
#define NV_AXISW2MC_SW_ID                   141
#define NV_EQOSR2MC_SR_ID                   142
#define NV_EQOSW2MC_SW_ID                   143
#define NV_UFSHCR2MC_SR_ID                  144
#define NV_UFSHCW2MC_SW_ID                  145
#define NV_NVDISPLAYR2MC_SR_ID              146
#define NV_BPMPR2MC_SR_ID                   147
#define NV_BPMPW2MC_SW_ID                   148
#define NV_BPMPDMAR2MC_SR_ID                149
#define NV_BPMPDMAW2MC_SW_ID                150
#define NV_AONR2MC_SR_ID                    151
#define NV_AONW2MC_SW_ID                    152
#define NV_AONDMAR2MC_SR_ID                 153
#define NV_AONDMAW2MC_SW_ID                 154
#define NV_SCER2MC_SR_ID                    155
#define NV_SCEW2MC_SW_ID                    156
#define NV_SCEDMAR2MC_SR_ID                 157
#define NV_SCEDMAW2MC_SW_ID                 158
#define NV_APEDMAR2MC_SR_ID                 159
#define NV_APEDMAW2MC_SW_ID                 160
#define NV_NVDISPLAYR12MC_SR_ID             161
#define NV_VICSRD12MC_SR_ID                 162
#define NV_MIU0R2MC_SR_ID                   166
#define NV_MIU0W2MC_SW_ID                   167
#define NV_MIU1R2MC_SR_ID                   168
#define NV_MIU1W2MC_SW_ID                   169
#define NV_MIU2R2MC_SR_ID                   174
#define NV_MIU2W2MC_SW_ID                   175
#define NV_MIU3R2MC_SR_ID                   176
#define NV_MIU3W2MC_SW_ID                   177
#define NV_MIU4R2MC_SR_ID                   178
#define NV_MIU4W2MC_SW_ID                   179
#define NV_VIFALR2MC_SR_ID                  188
#define NV_VIFALW2MC_SW_ID                  189
#define NV_DLA0RDA2MC_SR_ID                 190
#define NV_DLA0FALRDB2MC_SR_ID              191
#define NV_DLA0WRA2MC_SW_ID                 192
#define NV_DLA0FALWRB2MC_SW_ID              193
#define NV_DLA1RDA2MC_SR_ID                 194
#define NV_DLA1FALRDB2MC_SR_ID              195
#define NV_DLA1WRA2MC_SW_ID                 196
#define NV_DLA1FALWRB2MC_SW_ID              197
#define NV_PVA0RDA2MC_SR_ID                 198
#define NV_PVA0RDB2MC_SR_ID                 199
#define NV_PVA0RDC2MC_SR_ID                 200
#define NV_PVA0WRA2MC_SW_ID                 201
#define NV_PVA0WRB2MC_SW_ID                 202
#define NV_PVA0WRC2MC_SW_ID                 203
#define NV_RCER2MC_SR_ID                    210
#define NV_RCEW2MC_SW_ID                    211
#define NV_RCEDMAR2MC_SR_ID                 212
#define NV_RCEDMAW2MC_SW_ID                 213
#define NV_PCIE0R2MC_SR_ID                  216
#define NV_PCIE0W2MC_SW_ID                  217
#define NV_PCIE1R2MC_SR_ID                  218
#define NV_PCIE1W2MC_SW_ID                  219
#define NV_PCIE2AR2MC_SR_ID                 220
#define NV_PCIE2AW2MC_SW_ID                 221
#define NV_PCIE3R2MC_SR_ID                  222
#define NV_PCIE3W2MC_SW_ID                  223
#define NV_PCIE4R2MC_SR_ID                  224
#define NV_PCIE4W2MC_SW_ID                  225
#define NV_PCIE5R2MC_SR_ID                  226
#define NV_PCIE5W2MC_SW_ID                  227
#define NV_ISPFALW2MC_SW_ID                 228
#define NV_DLA0RDA12MC_SR_ID                233
#define NV_DLA1RDA12MC_SR_ID                234
#define NV_PVA0RDA12MC_SR_ID                235
#define NV_PVA0RDB12MC_SR_ID                236
#define NV_PCIE5R12MC_SR_ID                 239
#define NV_NVENCSRD12MC_SR_ID               240
#define NV_ISPRA12MC_SR_ID                  242
#define NV_MIU5R2MC_SR_ID                   252
#define NV_MIU5W2MC_SW_ID                   253
#define NV_MIU6R2MC_SR_ID                   254
#define NV_MIU6W2MC_SW_ID                   255
#define NV_JESD204TXIF0RD2MC_SR_ID          258
#define NV_JESD204TXIF1RD2MC_SR_ID          259
#define NV_JESD204RXIF0WR2MC_SW_ID          260
#define NV_JESD204RXIF1WR2MC_SW_ID          261
#define NV_JESD204RXIF2WR2MC_SW_ID          262
#define NV_JESD204RXIF3WR2MC_SW_ID          263
#define NV_JESD204TXCTRLRD2MC_SR_ID         264
#define NV_JESD204TXCTRLWR2MC_SW_ID         265
#define NV_JESD204RXCTRLRD2MC_SR_ID         266
#define NV_JESD204RXCTRLWR2MC_SW_ID         267
#define NV_JESD204TXIF0RD12MC_SR_ID         268
#define NV_JESD204TXIF1RD12MC_SR_ID         269
#define NV_MIU14R2MC_SR_ID                  274
#define NV_MIU14W2MC_SW_ID                  275
#define NV_LDPCDECAR2MC_SR_ID               280
#define NV_LDPCDECAR12MC_SR_ID              281
#define NV_LDPCDECAW2MC_SW_ID               282
#define NV_LDPCDECBR2MC_SR_ID               283
#define NV_LDPCDECBW2MC_SW_ID               284
#define NV_LDPCENCAR2MC_SR_ID               285
#define NV_LDPCENCAW2MC_SW_ID               287
#define NV_LDPCENCBR2MC_SR_ID               288
#define NV_LDPCENCBW2MC_SW_ID               289
#define NV_PMA0AWR2MC_SW_ID                 290
#define NV_NVJPG1SRD2MC_SR_ID               291
#define NV_NVJPG1SWR2MC_SW_ID               292
#define NV_MIU15R2MC_SR_ID                  294
#define NV_MIU15W2MC_SW_ID                  295
/* ICC master node */
#define TEGRA_ICC_MASTER		    400
/* Floor clients */
#define TEGRA_ICC_DEBUG			    401
#define TEGRA_ICC_CPU_CLUSTER0		    402
#define TEGRA_ICC_CPU_CLUSTER1		    403
#define TEGRA_ICC_CPU_CLUSTER2		    404

#endif /* _DT_BINDINGS_TEGRA_ICC_ID_H */
